using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

/*
Simple class attached to a button, showing one piece of vocabulary.
Buttons will be prefabs, generated by the vocab menu.
Button will show an image representing the vocab, and on click will call the vocab menu to show more details.
*/
public class VocabReviewButton : MonoBehaviour
{
    //Editor supplied pointer to the image on the button
    public Image buttonImage;

    //Word for this button
    private string m_Vocab;

    //Pointer to parent menu 
    private VocabReviewMenu m_Menu;

    /*
    Called on instantiation by parent menu supplying this instance's word, this function then looks up the appropriate picture.
    */
    public void SetVocab(string word, VocabReviewMenu menu)
    {
        m_Vocab = word;
        m_Menu = menu;
        buttonImage.sprite = Resources.Load<Sprite>("Images/" + m_Vocab);
    }

    /*
    Pass this word back up to parent menu to show more details in a popup menu
    */
    public void ShowDetails()
    {
        m_Menu.ShowVocabDetails(m_Vocab);
    }
}
